### ISSUE TITLE
Remove SDK download step

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-package-publisher#33]
Remove the expectation for the job to have uploaded assets with specific structure and naming. Instead, assume that the SDKs are just in the standard place on disk already.

This allows this action to be used in any workflow that uses the standard provider file layout, even if it doesn't use ci-mgmt, but more imporantly simplified the expected interface to be inputs & files on disk.

**Comment by t0yv0** [comment]
Or make it an explicit parameter to make it obvious it's an input to this? 

From:

```
    - name: Publish SDKs
      uses: pulumi/pulumi-package-publisher@v0.0.20
      with:
        sdk: all
        version: ${{ inputs.version }}
```

To:

```
    - name: Publish SDKs
      uses: pulumi/pulumi-package-publisher@v0.0.20
      with:
        sdk: all
        version: ${{ inputs.version }}
        artifacts:
          nodejs: nodejs-sdk.tar.gz
```
