### ISSUE TITLE
Allows to pass in parameter the gradle version for publishing Java SDK

### ISSUE THREAD

**Issue by scraly** [pulumi/pulumi-package-publisher#46]
## Issue details

This GH action is using an hardcoded and fixed version of Gradle:
```
   gradle-version: 7.4.1
```

### Affected area/feature

It causes an error when a provider use Java 21 and Gradle 8.8 for example.
Hardcoding an old version of Gradle (and Java) is not safe and user friendly.
So my purpose is to allow to customize the gradle version in a "with" statement:

```
      with:
        sdk: all
        version: ${{ inputs.version }}
        gradle-version: "8.8"
```

Thank you
